# Generated by Django 3.2.4 on 2021-06-18 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(max_length=120)),
                ('telefone', models.IntegerField(max_length=12)),
                ('dataPedido', models.DateField(auto_now_add=True)),
                ('dataFesta', models.DateField()),
                ('Rua', models.CharField(max_length=300)),
                ('Num', models.IntegerField(max_length=6)),
                ('Tema', models.TextField()),
                ('HoraInicio', models.DecimalField(decimal_places=2, max_digits=2)),
                ('Aluguel', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AddItem', models.CharField(max_length=300)),
                ('festaItems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.festa')),
            ],
        ),
    ]
