# Generated by Django 3.2.4 on 2021-06-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festa',
            name='HoraInicio',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='festa',
            name='Num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='festa',
            name='telefone',
            field=models.CharField(max_length=12),
        ),
    ]
