# Generated by Django 3.2.4 on 2021-06-19 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210619_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itens',
            name='festaItems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='main.festa'),
        ),
    ]
