# Generated by Django 3.2.4 on 2021-06-19 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_itens_festaitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itens',
            old_name='festaItems',
            new_name='FestaItens',
        ),
        migrations.AddField(
            model_name='festa',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itens',
            name='AddItem',
            field=models.TextField(),
        ),
    ]
