# Generated by Django 3.2.4 on 2021-06-16 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_prioridade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('data_limite_execucao', models.DateField(blank=True)),
                ('detalhamento', models.TextField()),
                ('percentual_conclusao', models.DecimalField(decimal_places=2, max_digits=3)),
                ('status', models.CharField(choices=[('a', 'Ativa'), ('c', 'Concluida')], max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('descricao', models.TextField()),
                ('data_execucao', models.DateField(blank=True)),
                ('slug', models.SlugField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='main.tarefa')),
            ],
        ),
    ]
