# Generated by Django 3.2.4 on 2021-06-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_tarefa_data_limite_execucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_limite_execucao',
            field=models.DateField(),
        ),
    ]
