# Generated by Django 3.2.4 on 2021-06-16 21:13

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tarefa_data_limite_execucao'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tarefa',
            managers=[
                ('ativa', django.db.models.manager.Manager()),
            ],
        ),
    ]
